### PR TITLE
Environment variables for easier modification

### PR DESCRIPTION
**Pull request by hackerb9**
I rewrote the Pygments module so that the keywords weren't hardcoded. Instead, it now looks for environment variables.

### CODE REVIEW

**Comment by FSund** [comment]
Is there an issue with the pdf example? I'm not seeing the custom keywords being highlighted.

image

**Comment by hackerb9** [comment]
> Is there an issue with the pdf example? I'm not seeing the custom keywords being highlighted.
>

🤪 And this is why one should never check-in code at one in the morning...

**Comment by hackerb9** [comment]
Okay, I reran `make` and created the correct PDF output. 

The previous file was from a test I had been running to ensure that my code didn't cause additional problems when the environment variables were omitted.

**Review by FSund — APPROVED** [review]
Looks good to me.

A further improvement could be to add a test that checks that all the environment variables works as intended.

**Pull request merged**
